### ISSUE TITLE
The location of the settings.json

### ISSUE THREAD

**Issue by arvinddeshpande** [tylerjwoodfin/securedata#1]
Frankly, I had been playing around with this package and try to build it and use it a little here's what I noticed.

- Did "pip install securedata" and then ran "securedata config" - which should take the path where to store the file. It only accepts the full path.
- When I entered "~/securedata" I was under the assumption that this is going to create the file under my home directoy. But look at the contents of 
```
p@raspberrypi:~/Git/securedata $ securedata config
Enter the full path of where you want to store all data:
~/securedata


Updated configuration.
pi@raspberrypi:~/Git/securedata $ cat ~/.local/lib/python3.9/site-packages/securedata/config.json
{
    "securePath": "/~/securedata"
}pi@raspberrypi:~/Git/securedata $

pi@raspberrypi:~/Git/securedata $ cat /~/securedata/settings.json
cat: /~/securedata/settings.json: No such file or directory
pi@raspberrypi:~/Git/securedata $ cat ~/securedata/settings.json
{
    "path_log": "/home/pi/securedata/log"
}pi@raspberrypi:~/Git/securedata $
```

- I think the larger problem is if a root user installs this module to be used by multiple people, which means it's global module. What if there are 2 different users that are running "securedata config"? Looks like the last user wins.

**Comment by tylerjwoodfin** [comment]
I changed this to allow tilde expressions (~/securedata) in [my newest commit](https://github.com/tylerjwoodfin/securedata/commit/9ccf470d835e3a8bdfd2256de06f966191498597)

I also added some warnings about the risks of using them and added a warning if the entered path doesn't exist.

**Comment by tylerjwoodfin** [comment]
@arvinddeshpande Because I changed the key in the config from `securePath` to `path_securedata`, when you update to the newest build, you may need to re-run the config (or manually edit the file) if you want to store your data outside of ~/securedata (which is the fallback location if the key isn't found)
